name: node_workflow

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: rsync
        uses: burnett01/rsync-deployments@5.2.1
        with:
          tool-cache: true
          switches: -avzr --delete
          path: dist/
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USER }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_path: /home/developer/deploy/front/static
