name: node_workflow

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Push to production
        run: rsync -avz ./dist/ ${{ secrets.USER }}@${{ secrets.HOST }}:/home/developer/deploy/front/static
